name: build

on:
  push:
      branches:
        - 'master'
  pull_request: ~

jobs:
    test:
        name: "Test (PHP ${{ matrix.php-versions }}, Neos ${{ matrix.flow-versions }})"

        strategy:
            fail-fast: false
            matrix:
                php-versions: []
                flow-versions: []
                include:
                  - php-versions: '7.3'
                    flow-versions: '7.3'
                  - php-versions: '8.0'
                    flow-versions: '8.0'
                  - php-versions: '8.1'
                    flow-versions: '8.1'

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: ${{ env.FLOW_FOLDER }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite
                  ini-values: date.timezone="Africa/Tunis", opcache.fast_shutdown=0, apc.enable_cli=on

            - name: Set Neos Version
              run: composer require neos/flow ^${{ matrix.flow-versions }} --no-progress --no-interaction

            - name: Run Tests
              run: composer test
